project:
  type: website
  output-dir: docs

website:
  title: "Predicting S&P 500 Returns"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Final Report"
        href: report.qmd
      - text: "Interactive Visualizations"
        href: interactive-viz.qmd
      - text: "About"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/lijack032/JSC370-Project
        target: _blank
  page-footer:
    center: "JSC370 Final Project | Mia Chen | 2026"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: right
    code-overflow: scroll
    css: styles.css

execute:
  echo: false
  warning: false
  message: false
jupyter: python3